use_frameworks!

platform :ios, '8.0'

target 'ZMJRouter_Example' do
  pod 'ZMJRouter', :path => '../'

  pod 'Masonry', '~> 1.1.0'
  
  target 'ZMJRouter_Tests' do
    inherit! :search_paths

    
  end
end
